baseURL = "/"
languageCode = "en-us"
title = "simple blog"
theme = "simple"
publishDir = "docs"


[[menu.main]]
  name = "food"
  weight = -70
  url = "/food"

[[menu.main]]
  name = "about"
  weight = -70
  url = "/about"

[[menu.main]]
  name = "drinks"
  weight = -60
  url = "/drinks"
